services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: invoicing_sys
      POSTGRES_PASSWORD: rAwT0IKcn4GMf
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: eFp0xCrRElmtv7b1k
    ports:
      - 8000:80